/*
   This file has been generated by IDA.
   It contains local type definitions from
   the type library 'H1Z1.exe'
*/

#define __int8 char
#define __int16 short
#define __int32 int
#define __int64 long long
#define _BYTE char
#define byte char
#define _WORD short
#define _DWORD int
#define _QWORD long long

struct ProxiedCharacter;
struct GameServer;
struct LoginRelatedClass;
struct LoginRelatedSubClass;

/* 427 */
struct __declspec(align(16)) BaseClient
{
  __int64 vtablePtr;
  _BYTE gap8[201417];
  _BYTE byte312D1;
  _BYTE gap312D2[470];
  GameServer *GameServer;
  _DWORD clientRunState;
  _QWORD qword314B8;
  _BYTE gap314C0[4];
  _DWORD dword314C4;
  __declspec(align(16)) _QWORD qword314D0;
  _BYTE gap314D8[32];
  _QWORD qword314F8;
  _BYTE gap31500[48];
  __int64 int6431530;
  __int64 int6431538;
  _DWORD dword31540;
  _BYTE gap31544[204];
  char *zoneServerAddressPtr;
  _BYTE gap31618[152];
  char *ticketPtr;
  _BYTE gap316B8[152];
  _QWORD qword31750;
  _BYTE gap31758[1680];
  _QWORD qword1;
  _BYTE gap31DF0[4];
  unsigned int loginConnectTimeout;
  unsigned int loginRetryCount;
  _BYTE gap31DFC[27140];
  _QWORD qword38800;
  _BYTE gap38808[28];
  _DWORD dword38824;
  _BYTE gap38828[16];
  _BYTE failedToLoginToGameServer;
  _BYTE clientIsRunning;
  _BYTE someByteFlag;
  char zoneDoneSendingInitialData;
  char receivedPreloadDonePacket;
  char field_3883D;
  char field_3883E;
  char field_3883F;
  char networkProximityUpdateComplete;
  byte gap38841[7];
  char waitForZoneReadyPacket;
  _BYTE gap38849[23];
  _QWORD proxiedCharacterPtr;
  _BYTE gap38868[96];
  _QWORD qword388C8;
  __int64 qword388D0;
  __int64 qword388D8;
  __int64 qword388E0;
  __int64 qword388E8;
  __int64 qword388F0;
  __int64 qword388F8;
  __int64 qword38900;
  __int64 qword38908;
  __int64 qword38910;
  __int64 qword38918;
  __int64 qword38920;
  __int64 qword38928;
  __int64 qword38930;
  __int64 qword38938;
  __int64 qword38940;
  __int64 qword38948;
  __int64 qword38950;
  __int64 qword38958;
  __int64 qword38960;
  __int64 qword38968;
  __int64 abilityBaseClass;
  __int64 qword38978;
  int dword38980;
  int field_38984;
  __int64 field_38988;
  __int64 field_38990;
  __int64 field_38998;
  _BYTE gap389A0[296];
  _QWORD qword38AC8;
  _QWORD qword38AD0;
  _BYTE gap38AD8[152];
  _QWORD qword38B70;
  __declspec(align(16)) LoginRelatedClass *LoginRelatedClass;
  _QWORD qword38B88;
  _BYTE gap38B90[88];
  _DWORD cypherType;
  _QWORD guid;
  _BYTE sendselfUnknownUint1[16];
  _QWORD qword2;
  _BYTE gap38C10[674];
  _BYTE ZoneIsLoadedFlagMaybe;
  _BYTE gap38EB3[205];
  _QWORD qword38F80;
  _BYTE gap38F88[344];
  _QWORD qword390E0;
  _BYTE gap390E8[9680];
  _QWORD qword3B6B8;
  _BYTE gap3B6C0[176];
  _BYTE someZoneRelatedFlag;
  _QWORD qword3B778;
  _BYTE gap3B780[92];
  _BYTE byte3B7DC;
  _BYTE gap3B7DD[491];
  _QWORD qword3B9C8;
  _BYTE gap3B9D0[29816];
  _QWORD ClientTwitchManager;
};

/* 430 */
struct __declspec(align(8)) GameServer
{
  _QWORD qword0;
  _BYTE gap8[3960];
  ProxiedCharacter *ProxiedCharacter;
};

/* 434 */
struct __declspec(align(8)) LoginRelatedClass
{
  _BYTE gap0[16];
  LoginRelatedSubClass *LoginRelatedSubClass;
  _BYTE gap18[188];
  _DWORD loginRetryCount;
  int intD8;
  _BYTE gapDC[125];
  _BYTE loginRetryCountRelatedBool;
  _BYTE gap15A[1];
  _BYTE byte15B;
  _WORD word15C;
  _BYTE byte15E;
  _QWORD qword160;
};

/* 424 */
struct __declspec(align(4)) ProxiedCharacter
{
  __int64 int640;
  _BYTE gap8[8];
  _QWORD guid;
  _QWORD characterId;
  _BYTE unknownUint1[8];
  __int64 identity;
  _BYTE gap30[272];
  _DWORD dword140;
  _BYTE gap144[52];
  _DWORD dword178;
  _BYTE byte17C;
  _BYTE byte17D;
  __declspec(align(4)) _DWORD dword180;
  _DWORD dword184;
  _BYTE gap188[4];
  _BYTE byte18C;
  __declspec(align(4)) _DWORD dword190;
  _DWORD dword194;
  _DWORD dword198;
  _BYTE gap19C[20];
  _DWORD dword1B0;
  _BYTE gap1B4[20];
  _DWORD dword1C8;
  _BYTE gap1CC[20];
  _DWORD dword1E0;
  _BYTE gap1E4[4];
  _DWORD dword1E8;
  _DWORD dword1EC;
  _BYTE gap1F0[240];
  _DWORD positionFloatVector4[4];
  _DWORD rotationFloatVector4[4];
  _DWORD dword300;
  _BYTE byte304;
  __declspec(align(4)) _DWORD dword308;
  _BYTE gap30C[12];
  _QWORD qword318;
  _QWORD qword320;
  _BYTE gap328[38608];
  _DWORD dword99F8;
  _BYTE gap99FC[188];
  _QWORD qword9AB8;
  _DWORD dword9AC0;
  _DWORD dword9AC4;
  _BYTE gap9AC8[44];
  _DWORD dword9AF4;
  _DWORD dword9AF8;
  _BYTE gap9AFC[60];
  _DWORD dword9B38;
  _BYTE gap9B3C[1452];
  _BYTE byteA0E8;
  _BYTE gapA0E9[2779];
  _DWORD actorModelId;
  _DWORD dwordABC8;
  _DWORD dwordABCC;
  _DWORD headId;
  _DWORD unknownDword6;
  _DWORD factionId;
  _DWORD dwordABDC;
  _DWORD dwordABE0;
  _BYTE gapABE4[4];
  __int64 headActor;
  _BYTE gapABF0[16];
  __int64 unknownString1;
  _BYTE gapAC08[16];
  __int64 int64AC18;
  _BYTE gapAC20[16];
  __int64 int64AC30;
  _BYTE gapAC38[16];
  __int64 int64AC48;
  _BYTE gapAC50[7632];
  _QWORD qwordCA20;
  _BYTE gapCA28[8];
  _QWORD qwordCA30;
  _QWORD qwordCA38;
  _QWORD qwordCA40;
  _QWORD qwordCA48;
  _BYTE gapCA50[8];
  _DWORD dwordCA58;
  _BYTE gapCA5C[180];
  _QWORD qwordCB10;
  _BYTE gapCB18[112];
  _QWORD qwordCB88;
  _QWORD qwordCB90;
  _DWORD dwordCB98;
  _BYTE gapCB9C[3820];
  _QWORD qwordDA88;
  _BYTE gapDA90[904];
  _QWORD qwordDE18;
  _QWORD qwordDE20;
  _DWORD dwordDE28;
  _BYTE gapDE2C[2348];
  _QWORD qwordE758;
  _DWORD dwordE760;
  _BYTE gapE764[284];
  _QWORD qwordE880;
  _BYTE gapE888[2736];
  _QWORD qwordF338;
  _QWORD qwordF340;
  _BYTE gapF348[1136];
  _DWORD dwordF7B8;
  _BYTE gapF7BC[116];
  _DWORD dwordF830;
  _BYTE gapF834[36];
  _DWORD dwordF858;
  _BYTE gapF85C[580];
  _QWORD qwordFAA0;
  _BYTE gapFAA8[3120];
  _QWORD qword106D8;
  _BYTE gap106E0[144];
  _QWORD qword10770;
  _BYTE gap10778[496];
  _QWORD qword10968;
  _BYTE gap10970[104];
  _BYTE byte109D8;
  _BYTE byte109D9;
  _BYTE byte109DA;
  _BYTE byte109DB;
};

/* 439 */
struct __declspec(align(1)) LoginRelatedSubClass
{
  __int16 gap0;
  _BYTE gap2[698];
  char someByteFlag;
  char someByteFlag2;
  _BYTE someByteFlag1;
};

/* 433 */
struct __declspec(align(4)) identity
{
	__int64 characterFirstName;
	_BYTE characterName[40];
	__int64 characterLastName;
	_BYTE combinedNameMaybe[104];
	__int64 nameRelatedMaybe;
	_BYTE gapA8[40];
	__int64 nameRelatedMaybe_0;
	_BYTE gapD8[40];
	_QWORD qword100;
	_DWORD characterId;
	_DWORD accountId;
	_DWORD unknownDword3;
};

/* 464 */
struct __declspec(align(1)) LightweightPc
{
	_BYTE gap0[8];
	_BYTE unknownByte1;
	_BYTE gap9[7];
	_QWORD guid;
	_BYTE transientId[8];
	identity identity;
	_BYTE gap134[4];
	_DWORD unknownByte2;
	_DWORD unknownDword1;
	_DWORD unknownDword2;
	_DWORD positionFloatVector3[3];
	_DWORD rotationFloatVector4[4];
	_DWORD unknownDword3;
	_BYTE gap164[4];
	_QWORD unknownQword1;
	_DWORD unknownDword4;
	_DWORD unknownDword5;
	_BYTE unknownByte3;
	_BYTE gap179[3];
	_DWORD unknownDword6;
	_DWORD unknownDword7;
	_BYTE gap184[4];
	_QWORD unknownQword2;
	_DWORD unknownDword8;
	_BYTE unknownByte4;
};

struct /*__declspec(align(2))*/ itemDefinitionStruct1
{
	_BYTE gap0[8];
	_DWORD dword8;
	_BYTE gapC[4];
	_DWORD dword10;
	_DWORD dword14;
	_DWORD dword18;
	_BYTE gap1C[12];
	_DWORD dword28;
	_DWORD dword2C;
	_DWORD dword30;
	_DWORD dword34;
	_DWORD dword38;
	_DWORD dword3C;
	_DWORD dword40;
	_DWORD dword44;
	__int64 int6448;
	_BYTE gap50[16];
	__int64 int6460;
	_BYTE gap68[16];
	__int64 int6478;
	_BYTE gap80[16];
	__int64 int6490;
	_BYTE gap98[16];
	_DWORD dwordA8;
	_DWORD dwordAC;
	_DWORD dwordB0;
	_DWORD dwordB4;
	_DWORD dwordB8;
	_DWORD dwordBC;
	_DWORD dwordC0;
	_DWORD dwordC4;
	_DWORD dwordC8;
	_DWORD dwordCC;
	_DWORD dwordD0;
	_DWORD dwordD4;
	_DWORD dwordD8;
	_DWORD dwordDC;
	_DWORD dwordE0;
	_DWORD dwordE4;
	_DWORD dwordE8;
	_DWORD dwordEC;
	_DWORD dwordF0;
	_DWORD dwordF4;
	_DWORD dwordF8;
	_DWORD dwordFC;
	_DWORD dword100;
	_DWORD dword104;
	__int64 int64108;
	_BYTE gap110[16];
	__int64 int64120;
	_BYTE gap128[16];
	_DWORD dword138;
	_DWORD dword13C;
	_DWORD dword140;
	_DWORD dword144;
	_DWORD dword148;
	_DWORD dword14C;
	_DWORD dword150;
	_DWORD dword154;
	_DWORD dword158;
	_DWORD dword15C;
	_DWORD dword160;
	_BYTE gap164[4];
	__int64 int64168;
	_BYTE gap170[16];
	_DWORD dword180;
	_BYTE gap184[4];
	_DWORD dword188;
	_DWORD dword18C;
	_DWORD dword190;
	_BYTE gap194[12];
	_BYTE byte1A0;
	_BYTE byte1A1;
};

struct __declspec(align(2)) DataLoadByPacket
{
	char* _buffer;
	int bufferSize;
	_BYTE gapC[4];
	char* pBuffer;
	char* pBufferEnd;
	__int16 failureFlag;
};

struct IncomingPacket
{
	BYTE gap0[8];
	DWORD packetType;
};


/* 489 */
struct __declspec(align(2)) BaseItemDefinition
{
	char qword0;
	_BYTE gap1[7];
	_DWORD dword8;
	_BYTE bitflags[2];
	_BYTE gapE[2];
	int NAME_ID;
	int DESCRIPTION_ID;
	_DWORD CONTENT_ID;
	_BYTE gap1C[4];
	int qword20;
	int field_24;
	int IMAGE_SET_ID;
	int TINT_ID;
	int HUD_IMAGE_SET_ID;
	int field_34;
	int qword38;
	int COST;
	int ITEM_CLASS;
	int PROFILE_OVERRIDE;
	__int64 MODEL_NAME;
	int qword50;
	int field_54;
	int qword58;
	int field_5C;
	__int64 TEXTURE_ALIAS;
	int qword68;
	int field_6C;
	int qword70;
	int field_74;
	__int64 TINT_ALIAS;
	int qword80;
	int field_84;
	int qword88;
	int field_8C;
	__int64 unknownString7;
	//int field_94;
	int qword98;
	int field_9C;
	int qwordA0;
	int field_A4;
	_DWORD GENDER_USAGE;
	_DWORD dwordAC;
	int CATEGORY_ID;
	int WEAPON_TRAIL_EFFECT_ID;
	int COMPOSITE_EFFECT_ID;
	int POWER_RATING;
	int MIN_PROFILE_RANK;
	int RARITY;
	int ACTIVATABLE_ABILITY_ID;
	int ACTIVATABLE_ABILITY_SET_ID;
	int PASSIVE_ABILITY_ID;
	int PASSIVE_ABILITY_SET_ID;
	_DWORD MAX_STACK_SIZE;
	int MIN_STACK_SIZE;
	int TINT_GROUP_ID;
	_DWORD MEMBER_DISCOUNT;
	_DWORD VIP_RANK_REQUIRED;
	int RACE_SET_ID;
	int UI_MODEL_CAMERA_ID;
	int EQUIP_COUNT_MAX;
	int CURRENCY_TYPE;
	_DWORD DATASHEET_ID;
	_DWORD ITEM_TYPE;
	_DWORD SKILL_SET_ID;
	__int64 OVERLAY_TEXTURE;
	int qword110;
	int field_114;
	int qword118;
	int field_11C;
	__int64 DECAL_SLOT;
	//int field_124;
	int qword128;
	int field_12C;
	int qword130;
	int field_134;
	int OVERLAY_ADJUSTMENT;
	int TRIAL_DURATION_SEC;
	int NEXT_TRIAL_DELAY_SEC;
	int CLIENT_USE_REQUIREMENT_ID;
	int unknownDword42;
	int unknownDword43;
	int unknownDword44;
	int BULK;
	_DWORD ACTIVE_EQUIP_SLOT_ID;
	_DWORD PASSIVE_EQUIP_SLOT_ID;
	_DWORD PASSIVE_EQUIP_SLOT_GROUP_ID;
	_DWORD INTERACTION_ANIMATION_ID;
	__int64 OVERRIDE_APPEARANCE;
	//int field_16C;
	int qword170;
	int field_174;
	int qword178;
	int field_17C;
	int OVERRIDE_CAMERA_ID;
	int USE_ITEM_RETICLE_ID;
	int unknownDword49;
	int GRINDER_REWARD_SET_ID;
	int BUILD_BAR_GROUP_ID;
	int field_194;
	int qword198;
	int field_19C;
	char unknownBoolean1;
	char IS_ARMOR;
};

/* 490 */
struct __declspec(align(8)) ClientItemDefinition
{
	BaseItemDefinition baseitemdefinition0;
	_QWORD qword1A8;
	_QWORD qword1B0;
	_QWORD qword1B8;
	_QWORD qword1C0;
	_QWORD qword1C8;
	_QWORD qword1D0;
	_QWORD PLAYER_STUDIO_DISPLAY_NAME;
	_QWORD qword1E0;
	_QWORD qword1E8;
	_QWORD qword1F0;
	_QWORD qword1F8;
	int field_200;
	int SCRAP_VALUE_OVERRIDE;
	_QWORD qword208;
	_QWORD qword210;
	_QWORD qword218;
	_QWORD qword220;
	_DWORD dword228;
	_DWORD dword22C;
	_QWORD qword230;
	_QWORD qword238;
	_DWORD dword240;
	_QWORD qword248;
};